---
# Example
# 8.1 https://gitpod.io/#TDK_PHP_VERSION=8.1,TDK_BRANCH=main,TDK_PATCH_REF=refs%2Fchanges%2F43%2F70643%2F36,TDK_USERNAME=ochorocho,TDK_PATCH_ID=70643/https://github.com/ochorocho/tdk/tree/main
# 8.0 https://gitpod.io/#TDK_PHP_VERSION=8.0,TDK_BRANCH=main,TDK_PATCH_REF=refs%2Fchanges%2F43%2F70643%2F36,TDK_USERNAME=ochorocho,TDK_PATCH_ID=70643/https://github.com/ochorocho/tdk/tree/main
# Detect php: https://gitpod.io/#TDK_BRANCH=11.5,TDK_PATCH_REF=refs%2Fchanges%2F43%2F70643%2F36,TDK_USERNAME=ochorocho,TDK_PATCH_ID=70643/https://github.com/ochorocho/tdk/tree/main
# https://gitpod.io/#TDK_BRANCH=11.5,TDK_PATCH_REF=refs%2Fchanges%2F43%2F70643%2F36,TDK_USERNAME=ochorocho,TDK_PATCH_ID=70643/https://github.com/ochorocho/tdk/tree/feature/add-ssh-command
# Composer Plugin: https://gitpod.io/#TDK_BRANCH=main,TDK_PATCH_REF=refs%2Fchanges%2F43%2F70643%2F36,TDK_USERNAME=ochorocho,TDK_PATCH_ID=70643/https://github.com/ochorocho/tdk/tree/feature/scripts-to-composer-plugin

image: ochorocho/gitpod-tdk:latest

tasks:
  - name: TDK
    init: |
      cp -Rp .gitpod/vscode .vscode
      cp -Rp .gitpod/phpstorm .idea
      tdk php "$(php .gitpod/php/version.php)" --no-reload
      gp open .gitpod/info.md
      composer tdk:git clone
      composer tdk:git checkout
      composer install
      composer tdk:git config
      composer tdk:hooks create --force
      composer tdk:git template --file=./.gitmessage.txt
      tdk ssh-add
      composer tdk:git apply
      composer install
      mkdir -p public/typo3conf
      touch public/FIRST_INSTALL
      cp -Rp .gitpod/typo3/AdditionalConfiguration.php public/typo3conf/AdditionalConfiguration.php
    command: |
      tdk ssh-add
      tdk php "$(php .gitpod/php/version.php)"
      sudo service mailhog start
      sudo service mysql start
      sudo service cron start
      sleep 5
      tdk db create
      composer tdk:help summary
      tdk preview fe

vscode:
  extensions:
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    # @todo: Installing sqltools does not work as expected
    #        it requires a window reload in some cases
    - mtxr.sqltools
    - mtxr.sqltools-driver-mysql

ports:
  - port: 3306
    name: database
    onOpen: ignore
  - port: 8001
    name: apache
    onOpen: ignore
  - port: 1025
    name: mailhog catcher
    onOpen: ignore
  - port: 8025
    name: mailhog
    onOpen: ignore
  - port: 9003
    name: xdebug
    description: xdebug
    onOpen: ignore
