#!/usr/bin/env bash

_tdk()
{
    local cur prev prev2 next

    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
    prev2=${COMP_WORDS[COMP_CWORD-2]}
    next=${COMP_WORDS[COMP_CWORD+1]}

    case ${COMP_CWORD} in
        1)
            COMPREPLY=($(compgen -W "cron preview db php" -- ${cur}))
            ;;
        2)
            case ${prev} in
                preview)
                    COMPREPLY=($(compgen -W "fe be install mailhog" -- ${cur}))
                    ;;
                db)
                    COMPREPLY=($(compgen -W "create delete" -- ${cur}))
                    ;;
                php)
                    ALL_VERSIONS=$(ls /etc/php)
                    COMPREPLY=($(compgen -W "${ALL_VERSIONS}" -- ${cur}))
                    ;;
            esac
            ;;
        3)
            case ${prev2} in
                php)
                        COMPREPLY=($(compgen -W "--no-reload" -- ${next}))
                    ;;
                esac
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _tdk tdk