#!/usr/bin/env bash

ARG=$1
DBNAME="db"

case $ARG in
  create)
    if [ -d /workspace/mysql/db ] ; then
      echo -e "Creating database.\n User: db\n Password: ${DBNAME}\n Host: localhost\n Name: db"
      sudo mysql -e "CREATE DATABASE ${DBNAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
      sudo mysql -e "CREATE USER '${DBNAME}'@'localhost' IDENTIFIED BY 'db';"
      sudo mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'db'@'localhost';"
      # mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"
    else
      echo -e "Database '${DBNAME}' already exists"
    fi

    exit 0
    ;;
  *)
    echo "Argument unknown. Choose one of the following:"
    echo "create"
    exit 1
    ;;
esac
