#!/usr/bin/env bash
_tdk()
{
    local cur prev

    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    case ${COMP_CWORD} in
        1)
            COMPREPLY=($(compgen -W "cron preview db php" -- ${cur}))
            ;;
        2)
            case ${prev} in
                preview)
                    COMPREPLY=($(compgen -W "fe be install mailhog" -- ${cur}))
                    ;;
                db)
                    COMPREPLY=($(compgen -W "create delete" -- ${cur}))
                    ;;
                php)
                    ALL_VERSIONS=$(ls /etc/php)
                    COMPREPLY=($(compgen -W "${ALL_VERSIONS}" -- ${cur}))
                    ;;
            esac
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _tdk tdk