#!/usr/bin/env bash

ARG=$1

PHP=${ARG:=8.1}
# @todo add help
ALL_VERSIONS=$(ls /etc/php)

if [[ ${ALL_VERSIONS[*]} =~ $PHP ]]
then
    echo "Switch to version $PHP."
else
    echo "PHP version $PHP not available, use 'tdk-php-switch <version>'"
    echo "These versions are available:"
    echo "${ALL_VERSIONS}"
    exit 1
fi

# Set CLI version
sudo update-alternatives --set php "$(which php${PHP})"

# Disable modules that might have been enabled, but conflicting
for version in $ALL_VERSIONS
do
    echo "Disable modules for PHP $version ..."
    sudo a2dismod mpm_prefork mpm_event mpm_worker > /dev/null 2>&1
    sudo a2dismod "php$version" > /dev/null 2>&1
done

sudo a2enmod "php$PHP" > /dev/null 2>&1

if [[ $2 = '--no-reload' ]]
then
    echo "Apache was not reloaded due to $2 option. Please reload manually using 'service apache2 restart'"
else
    sudo service apache2 restart
fi
