#!/usr/bin/env bash

ARG=$1
DBNAME="db"

# initialize database structures on disk, if needed
[ ! -d /workspace/mysql ] && mysqld --initialize-insecure

case $ARG in
  create)
    if [ -d /workspace/mysql/db ] ; then
      echo -e "Database '${DBNAME}' already exists"
    else
      echo -e "Creating database.\n User: db\n Password: ${DBNAME}\n Host: localhost\n Name: db"
      sudo mysql -e "CREATE DATABASE ${DBNAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
      sudo mysql -e "CREATE USER '${DBNAME}'@'localhost' IDENTIFIED BY '${DBNAME}';" > /dev/null 2>&1
      sudo mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'db'@'localhost';"
    fi

    exit 0
    ;;
  delete)
    if [ -d /workspace/mysql/db ] ; then
      sudo mysql -e "DROP DATABASE ${DBNAME};"
      echo -e "Database '${DBNAME}' deleted"
    else
      echo -e "Database '${DBNAME}' does not exist"
    fi

    exit 0
    ;;
  *)
    echo "Argument unknown. Choose one of the following:"
    echo "create"
    exit 1
    ;;
esac
