#!/usr/bin/env bash

ARG=$1

case $ARG in
  create)
    echo -e "Creating database.\n User: db\n Password: db\n Host: localhost\n Name: db"
    mysql -e "CREATE DATABASE db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
    mysql -e "CREATE USER 'db'@'localhost' IDENTIFIED BY 'db';"
    mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'db'@'localhost';"
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"
    exit 0
    ;;
  *)
    echo "Argument unknown ..."
    exit 1
    ;;
esac
