#!/usr/bin/env bash

ARG=$1

case $ARG in
  fe)
    gp preview "$(gp url 8001)" --external
    exit 0
    ;;
  be)
    gp preview "$(gp url 8001)/typo3" --external
    exit 0
    ;;
  install)
    touch \$GITPOD_REPO_ROOT/public/typo3conf/ENABLE_INSTALL_TOOL && gp preview "$(gp url 8001)/typo3/install.php" --external
    exit 0
    ;;
  mailhog)
    gp preview "$(gp url 8025)" --external
    exit 0
    ;;
  *)
    echo "Unknown preview command. Choose one of the following:"
    echo "fe, be, install, mailhog"
    exit 1
    ;;
esac
