name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 1"

jobs:
  build:
    name: Build and Push Container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.1 ]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Docker info
        run: docker info
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Check out code
        uses: actions/checkout@v1
      -
        name: "Build ${{ matrix.php-version }} image"
        shell: 'script -q -e -c "bash {0}"'
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx create --use --platform=linux/arm64,linux/amd64
          cd ./.gitpod/docker/
          ./build.sh -v ${{ matrix.php-version }} -p
