name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
jobs:
  testsuite:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker version

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-all --no-check-lock

      - name: Install docker
        run: sudo apt update && sudo apt install -y docker

      - name: Install ddev
        run: curl https://apt.fury.io/drud/gpg.key | sudo apt-key add - && echo "deb https://apt.fury.io/drud/ * *" | sudo tee -a /etc/apt/sources.list.d/ddev.list && sudo apt update && sudo apt install -y ddev

      - name: Install dependencies
        # Do a clone here to make sure the repository exists on install
        # to avoid missing repository error in composer.
        run: composer tdk:clone && composer install --no-progress

      - name: phpstan
        run:  ./vendor/bin/phpstan analyse -c .phpstan.neon --no-progress

      - name: php-cs-fixer
        run:  ./vendor/bin/php-cs-fixer fix -v --config=./.php_cs.php --using-cache no --diff --dry-run

      - name: Run acceptance tests
        run: ./vendor/bin/codecept run --html
  docker:
    name: Docker Image Builder
    runs-on: ubuntu-latest
    steps:
      - name: Run find-and-replace to remove slashes
        uses: mad9000/actions-find-and-replace-string@1
        id: clean_ref
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'

      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ochorocho/gitpod-tdk
          tags: |
            type=raw,value=${{ steps.clean_ref.outputs.value }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .gitpod/docker/
          load: true
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Test for expected binaries
        run: |
          echo ${{ steps.meta.outputs.tags }}
          echo ${GITHUB_WORKSPACE}
          docker run --rm -v ${GITHUB_WORKSPACE}/.gitpod/docker/test.sh:/tmp/test.sh --entrypoint "bash" ochorocho/gitpod-tdk:${{ steps.clean_ref.outputs.value }} /tmp/test.sh
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .gitpod/docker/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
